services:
  db:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: petadoption
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: