version: '3.8'

services:
  frontend:
    image: pet-adoption-frontend
    build:
      context: ../pet-adoption-frontend
      dockerfile: ../docker/pet-adoption-frontend.Dockerfile
    restart: always
    ports:
      - '3000:3000'
    networks:
      - internal

  db:
    image: mysql
    command: --mysql-native-password=ON
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: petadoption
    networks:
      - internal

  api:
    image: pet-adoption-api
    build:
      context: ../pet-adoption-api
      dockerfile: ../docker/pet-adoption-api.Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/petadoption
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - internal
    depends_on:
      - db

networks:
  internal:
    driver: bridge