version: '3.8'

services:
  frontend:
    build:
      context: ../pet-adoption-frontend
      dockerfile: ../docker/pet-adoption-frontend.Dockerfile
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ../pet-adoption-api
      dockerfile: ../docker/pet-adoption-api.Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/petadoption
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: petadoption
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
    driver: local
