services:
  frontend:
    image: pet-adoption-frontend
    build:
      context: ../pet-adoption-frontend
      dockerfile: ../docker/pet-adoption-frontend.Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://104.198.233.250:8080
    networks:
      - internal-network

  db:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 19ufni320fdn9f4n3nf40983nf89n9f843n9f043
      MYSQL_DATABASE: petadoption
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_TCP_PORT: 3307
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal-network

  api:
    image: pet-adoption-api
    build:
      context: ../pet-adoption-api
      dockerfile: ../docker/pet-adoption-api.Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/petadoption
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 19ufni320fdn9f4n3nf40983nf89n9f843n9f043
      FRONTEND_URL: http://104.198.233.250:3000
    networks:
      - internal-network
    depends_on:
      - db

networks:
  internal-network:
    driver: bridge

volumes:
  mysql-data:
