version: '3.8'

services:
  frontend:
    build:
      context: ../pet-adoption-frontend
      dockerfile: ../pet-adoption-frontend/Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - default

  backend:
    build:
      context: ../pet-adoption-api
      dockerfile: ../pet-adoption-api/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/petadoption?user=root&password=password
    networks:
      - default

  mysql:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: petadoption
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

volumes:
  mysql-data:
    driver: local

networks:
  default:
    external:
      name: docker_default
