version: '3.8'

services:
  frontend:
    build:
      context: ../pet-adoption-frontend
      dockerfile: ../pet-adoption-frontend/Dockerfile
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ../pet-adoption-api
      dockerfile: ../pet-adoption-api/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/petadoption?user=root&password=password

volumes:
  mysql-data:
    driver: local
