version: '3.8'

services:
  frontend:
    build:
      context: ../
      dockerfile: ../docker/pet-adoption-frontend.Dockerfile
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ../
      dockerfile: ../docker/pet-adoption-api.Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      DATABASE_URL: mysql://db:3306/petadoption

  db:
    image: mysql:8.4.2
    command: --mysql-native-password=ON
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: petadoption
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
