name: Zero Downtime Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker compose -f docker/production.docker-compose.yml build

      - name: Deploy new version without downtime
        run: |
          docker compose -f docker/production.docker-compose.yml up -d --no-deps --build --scale frontend=2 --scale api=2

      - name: wait for new instances to be up and running
        run: |
          sleep 10

      - name: Remove old instances after new ones are verified
        run: |
          docker compose -f docker/production.docker-compose.yml up -d --no-deps --scale frontend=1 --scale api=1
          docker compose -f docker/production.docker-compose.yml down --remove-orphans

      - name: Prune
        run: |
          docker image prune -af
          docker builder prune
