name: Sample Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: |
          # Build both frontend and backend images using the production Docker Compose file
          docker compose -f docker/production.docker-compose.yml build

      - name: Deploy
        run: |
          # Stop and remove any existing containers to avoid port conflicts
          docker compose -f docker/production.docker-compose.yml down
          
          # Deploy the newly built containers in detached mode
          docker compose -f docker/production.docker-compose.yml up -d --build
          
          # Clean up unused Docker images to free up space
          docker image prune -af
