name: Build and Deploy Frontend & Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Deploy to Production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}          # SSH username
          SSH_HOST: ${{ secrets.SSH_HOST }}          # SSH host (production server IP or domain)
        run: |
          # Set up SSH keys
          mkdir -p ~/.ssh
          echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Connect to the production server and deploy the updated containers
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            # Stop the old containers
            docker compose -f docker/production.docker-compose.yml down
            
            # Build and start the new containers
            docker compose -f docker/production.docker-compose.yml up -d --build
            
            # Clean up unused Docker images
            docker image prune -af
          EOF
