name: Build and Deploy Frontend & Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Cleanup Docker Resources
        run: |
          echo "Removing unused images"
          docker image prune -a -f

          echo "Removing unused volumes"
          docker volume prune -f

          echo "Removing unused networks"
          docker network prune -f

          echo "Cleaning up build cache"
          docker builder prune -a -f

      - name: Build Frontend Image
        run: |
          docker build -t wesley_goyette/pet-adoption-frontend:latest -f ./docker/pet-adoption-frontend.Dockerfile .

      - name: Build Backend Image
        run: |
          docker build -t wesley_goyette/pet-adoption-api:latest -f ./docker/pet-adoption-api.Dockerfile .

      - name: Start MySQL Container
        run: |
          docker rm -f pet-adoption-db || echo "No existing database container"
          docker run -d \
            --name pet-adoption-db \
            -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
            -e MYSQL_DATABASE=petadoption \
            -p 3306:3306 \
            -v mysql-data:/var/lib/mysql \
            mysql:8.0
        
      - name: Start Frontend Container
        run: |
          docker rm -f pet-adoption-frontend || echo "No existing frontend container"
          docker run -d --name pet-adoption-frontend -p 3000:3000 wesley_goyette/pet-adoption-frontend:latest

      - name: Start Backend Container
        run: |
          docker rm -f pet-adoption-backend || echo "No existing backend container"
          docker run -d --name pet-adoption-backend -p 8080:8080 wesley_goyette/pet-adoption-api:latest
