name: Build and Deploy Frontend & Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and start containers
        run: |
          docker-compose -f ci.docker-compose.yml build
          docker-compose -f ci.docker-compose.yml up -d

      - name: Wait for MySQL to be ready
        run: |
          timeout 60s bash -c 'until docker exec $(docker-compose -f ci.docker-compose.yml ps -q db) mysqladmin ping -h localhost -u root -ppassword --silent; do echo "Waiting for MySQL to be ready..."; sleep 2; done'

      - name: Check running containers
        run: docker ps

      - name: Check logs
        run: |
          echo "Frontend logs:"
          docker-compose -f ci.docker-compose.yml logs frontend
          echo "Backend logs:"
          docker-compose -f ci.docker-compose.yml logs api
          echo "Database logs:"
          docker-compose -f ci.docker-compose.yml logs db