name: Build and Deploy Frontend & Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Frontend Image
        run: |
          docker build -t yourusername/pet-adoption-frontend:latest -f ./docker/pet-adoption-frontend.Dockerfile .

      - name: Build Backend Image
        run: |
          docker build -t yourusername/pet-adoption-api:latest -f ./docker/pet-adoption-api.Dockerfile .

      - name: Push Frontend Image
        run: |
          docker push yourusername/pet-adoption-frontend:latest

      - name: Push Backend Image
        run: |
          docker push yourusername/pet-adoption-api:latest

      - name: Deploy to Production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no your_user@your_production_server << 'EOF'
            # Pull the latest images
            docker pull yourusername/pet-adoption-frontend:latest
            docker pull yourusername/pet-adoption-api:latest
            
            # Stop the old containers
            docker compose -f /path/to/docker-compose.prod.yml down
            
            # Start the new containers with updated images
            docker compose -f /path/to/docker-compose.prod.yml up -d --build
            
            # Clean up unused Docker images
            docker image prune -af
          EOF
